ALTER TABLE projects
    ADD COLUMN IF NOT EXISTS color VARCHAR(20) NOT NULL DEFAULT '#14b8a6';

ALTER TABLE workspace_members
    ADD COLUMN IF NOT EXISTS department VARCHAR(120),
    ADD COLUMN IF NOT EXISTS title VARCHAR(120),
    ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMP;

ALTER TABLE workspace_invitations
    ADD COLUMN IF NOT EXISTS department VARCHAR(120),
    ADD COLUMN IF NOT EXISTS title VARCHAR(120),
    ADD COLUMN IF NOT EXISTS invite_note VARCHAR(500);

ALTER TABLE research_runs
    ADD COLUMN IF NOT EXISTS progress INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS current_step VARCHAR(255),
    ADD COLUMN IF NOT EXISTS duration_seconds INTEGER,
    ADD COLUMN IF NOT EXISTS token_count BIGINT;

ALTER TABLE reports
    ADD COLUMN IF NOT EXISTS version_no VARCHAR(30) NOT NULL DEFAULT '1',
    ADD COLUMN IF NOT EXISTS lead TEXT,
    ADD COLUMN IF NOT EXISTS summary TEXT,
    ADD COLUMN IF NOT EXISTS recommendation VARCHAR(500),
    ADD COLUMN IF NOT EXISTS recommendation_detail TEXT,
    ADD COLUMN IF NOT EXISTS citations INTEGER NOT NULL DEFAULT 0;
