package com.cuupe.backend.modules.workspace.controller;
import com.cuupe.backend.common.Result; import com.cuupe.backend.common.exception.ApiException; import com.cuupe.backend.modules.audit.service.AuditLogService; import com.cuupe.backend.modules.user.security.UserLoginByPassword; import com.cuupe.backend.modules.workspace.entity.Workspace; import com.cuupe.backend.modules.workspace.mapper.WorkspaceMapper; import com.cuupe.backend.modules.workspace.service.WorkspaceService; import tools.jackson.databind.ObjectMapper; import jakarta.validation.Valid; import jakarta.validation.constraints.NotBlank; import lombok.RequiredArgsConstructor; import org.springframework.http.HttpStatus; import org.springframework.security.core.Authentication; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.util.LinkedHashMap; import java.util.List; import java.util.Map;
@RestController @RequestMapping("/workspaces") @RequiredArgsConstructor public class WorkspaceController { private final WorkspaceMapper mapper; private final WorkspaceService workspaceService; private final AuditLogService auditLogService; private final ObjectMapper objectMapper;
 @GetMapping("/my") public Result<List<Workspace>> list(Authentication auth){return Result.success(mapper.findByUser(userId(auth)));}
 @PostMapping public Result<Workspace> create(@Valid @RequestBody WorkspaceCreateRequest request,Authentication auth){Long uid=userId(auth);Workspace created=workspaceService.create(request.name(),request.code(),request.description(),uid);auditLogService.record(created.getId(),null,uid,"WORKSPACE_CREATED","WORKSPACE",created.getId(),Map.of("name",created.getName()));return Result.success(created);}
 @GetMapping("/{id}") public Result<Workspace> detail(@PathVariable Long id,Authentication auth){return Result.success(required(id,userId(auth)));}
 @PatchMapping("/{id}") public Result<Workspace> update(@PathVariable Long id,@Valid @RequestBody WorkspaceUpdateRequest request,Authentication auth){Long uid=userId(auth);Workspace workspace=required(id,uid);workspace.setName(request.name());workspace.setDescription(request.description());if(mapper.update(workspace,uid)==0)throw forbidden();auditLogService.record(id,null,uid,"WORKSPACE_UPDATED","WORKSPACE",id,Map.of("name",request.name()));return Result.success(required(id,uid));}
 @DeleteMapping("/{id}") @Transactional public Result<Void> delete(@PathVariable Long id,Authentication auth){Long uid=userId(auth);required(id,uid);if(mapper.changeStatus(id,uid,"DELETED")==0)throw forbidden();int deletedProjects=mapper.deleteProjects(id,uid);auditLogService.record(id,null,uid,"WORKSPACE_DELETED","WORKSPACE",id,Map.of("deletedProjectCount",deletedProjects));return Result.success();}
 @PatchMapping("/{id}/archive") public Result<Void> archive(@PathVariable Long id,Authentication auth){Long uid=userId(auth);Result<Void> result=change(id,uid,"ARCHIVED");auditLogService.record(id,null,uid,"WORKSPACE_ARCHIVED","WORKSPACE",id);return result;}
 @PatchMapping("/{id}/restore") public Result<Void> restore(@PathVariable Long id,Authentication auth){Long uid=userId(auth);Result<Void> result=change(id,uid,"ACTIVE");auditLogService.record(id,null,uid,"WORKSPACE_RESTORED","WORKSPACE",id);return result;}
 @PatchMapping("/{id}/preferences") public Result<Workspace> preferences(@PathVariable Long id,@RequestBody Map<String,Object> body,Authentication auth){Long uid=userId(auth);Workspace current=required(id,uid);Map<String,Object> preferences=new LinkedHashMap<>();if(current.getPreferences()!=null&&!current.getPreferences().isBlank())try{preferences.putAll(objectMapper.readValue(current.getPreferences(),Map.class));}catch(Exception ignored){}preferences.put("webSearch",Boolean.TRUE.equals(body.get("webSearch")));preferences.put("citationsRequired",Boolean.TRUE.equals(body.get("citationsRequired")));preferences.put("retention",String.valueOf(body.getOrDefault("retention",preferences.getOrDefault("retention","90 天"))));if(body.containsKey("agentPolicy"))preferences.put("agentPolicy",body.get("agentPolicy"));if(body.containsKey("localTools"))preferences.put("localTools",body.get("localTools"));String json;try{json=objectMapper.writeValueAsString(preferences);}catch(Exception e){throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_PREFERENCES","工作区偏好格式不正确");}if(mapper.updatePreferences(id,uid,json)==0)throw forbidden();auditLogService.record(id,null,uid,"WORKSPACE_PREFERENCES_UPDATED","WORKSPACE",id);return Result.success(required(id,uid));}
 private Result<Void> change(Long id,Long uid,String status){required(id,uid);if(mapper.changeStatus(id,uid,status)==0)throw forbidden();return Result.success();}
 private Workspace required(Long id,Long uid){Workspace value=mapper.findAccessible(id,uid);if(value==null)throw new ApiException(HttpStatus.NOT_FOUND,"WORKSPACE_NOT_FOUND","工作区不存在或无权访问");return value;}
 private Long userId(Authentication auth){return ((UserLoginByPassword)auth.getPrincipal()).getId();} private ApiException forbidden(){return new ApiException(HttpStatus.FORBIDDEN,"WORKSPACE_WRITE_FORBIDDEN","只有工作区所有者或管理员可以修改或删除工作区");}
 public record WorkspaceCreateRequest(@NotBlank String name,String code,String description){}
 public record WorkspaceUpdateRequest(@NotBlank String name,String description){}
}
